### ISSUE TITLE
Tucker's notes

### ISSUE THREAD

**Issue by tuckabelle** [CSIS-iLab/health-commission#135]
## General
- [x] add `-webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;`
-  [x] descrease space between page excerpt and photo caption `.page-highlights .page-highlights__col .page__excerpt{ margin-bottom: .5rem}`
- [x] increase padding around excerpt/photo caption box and featured post, but not download/cite/share `.page-highlights .page-highlights__col {padding: 2rem;}`
- [x] increase space at bottom on post content `.post__content{    margin: 0 auto 5rem;}`
- [x] hover on external link icons should be gold
- [x] ~can we get the series and content to stay on the same line, with long series names wrapping instead of moving the whole name to a new line?~
- [x] ital the series name after "from"
- [x] remove "Welcome to Jekyll Algolia!" post :)

## Footer
- [x] contact spacing
```css
.site-footer .site-footer__info .site-footer__contact-list li:not(:first-of-type):nth-of-type(n+3):before {
  left:-10%;
}
```

## Archive listing block
- [x] `h2.post-block__title{margin:.25rem 0}`
- [x] `.post-block__content p {margin:0 0 .25rem}`
- [x] `.post-block__header {    margin-bottom: .75rem;}`

## About the Commission
- [x] The image should be as wide as the caption
- [x] about table of contents `.about-table-contents ul {  padding-left: 1rem; }`

#### Desktop 
- [x] make short bios 16px; bio in popup stays 18px
- [x] decrease space between short bio and title `.members div[class$='member__text'] .bio-short, .members div[class$="member__text"] .bio-long { margin: .5rem 0 1.125rem;}`
- [x] popup: close 'x' turns gold on hover
- [x] popup modal: `height: 75vh` and center modal verically
- [x] popup `.modal {padding: 0.5rem 0.5rem 3rem 1.5rem}` 
- [x] `.authors-block__name, .members div[class$='member__text'] .bio-name:     line-height: 1.25;`
- [x] `.members__content .member-directory .group:not(:last-child) {margin-bottom: 3rem;`
- [x] 'Experts and Advisors' and 'Secretariat' should be `<h2>`
#### Mobile
- [x] modal should be in front of header... is there a way to disable header dropdown when modal is active?
- [x] when jumping by name, have top of photo + 1rem align with top of screen
- [x] users should be able to close lower the "navigate by name" panel if they click outside the panel. Right now the fade goes away, but the panel does not drop, and then the toggle is off. 
- [x] in 'navigate by name' panel: decrease top padding `.navigate-members__container {padding: .5rem 2rem 1.5rem}`
- [x] add box shadow to 'navigate by name' panel: `.navigate-members {box-shadow: 1px -2px 6px 0px rgba(140,137,140,0.4)}`]\
- [x] 'navigate by name' panel transition: 
```css
.navigate-members__container {
    height: 67vh;
    padding: .5rem 2rem 1.5rem;
    overflow-y: auto;
    transition: all 0.3s ease-in-out;
}
    .navigate-members__container.hide {
    /* display: none; */
    height: 0px;
    padding: 0px;
    transition: all 0.3s ease-in-out;
    }
```
- [x] text in modal is visible past padding

## Events
- [x] description is repeated
- [x] why is the main Events archive image different from the event post image?

## Theme archive page
- [x] let's remove the authors list for the top gold "featured post" box. they are listed on the bottom anyways
- [x] Can we show the selected theme without the rest of the dropdown being open when you click on "See more related posts" at the bottom of a theme page?

### Search Archive
- [x] theme names in the filter dropdown should not have letter-spacing
- [x] increase padding for elements in dropdown so there's 1rem on left/right
- [x] increase margin of lists section `.archive__content {    margin: 4rem auto}`
- [x] make "Search:" label color #D8D9DC and search text white
#### Mobile
- [x] decrease size of search line div/text font
- [x] can we close the dropdown if they click anywhere outside the div??

## Pagination
- [x] more space between line and pagination `.pagination__pagination .ais-pagination {margin-top: .5rem;}`
- [x] increase space between 'previous' or 'next' links and numbers by .75rem

## Post page
- [x] author image filter: `contrast(137%) brightness(80%) grayscale(100%) sepia(0.61) hue-rotate(176deg) saturate(67%)`
- [x] increase margin at bottom of past `.post__content {margin: 0 auto 5rem}`
- [x] -make sure the listings match up in the 'previous article' and 'related articles' ( the content types should horizontally aligned)
- [x] increase 'related articles' padding `.post__related-posts .related-by-tag {padding: 2rem 50px 2rem 4rem}`
#### Mobile
- [x] spacing between header date and summary box is too narrow
- [x] what happened to summary box gray background?
- [x] there should be a tad more space between tags/share and footer on pages that do not have authors or resources (i.e. "Health Security in a Disordered World")

## Homepage
- [x] increase space after "list all articles" button" `.home__articles-btn {padding: 0 2rem 5rem}`
#### Mobile
- [x] scale homepage map
```css
.home__hero .home__map {
width: 160vw;
    left: 25%;
}
```
- [x] Nice to have: switch site title and map order, hide header title on homepage only
```css
.home__hero .home__map {
top: 30%;
}

.home__hero-subtitle, .home__hero-title {
    top: -60%;
}

.home__desc {
    padding-top: 1rem;
}
```
<img width="374" alt="screen shot 2018-10-01 at 1 35 59 pm" src="https://user-images.githubusercontent.com/13002217/46305278-01695980-c57f-11e8-9ca9-1d9cbfa6e72d.png">

## Header
- [x] is it possible to have the links slide to the same place as title was once they slide?
#### Mobile
- [x] dropdown nav links don't work
- [x] scroll on the menu makes the header disappear 
- [x] logo title letter spacing
- [x] All Articles 
- [x] on dropdown hover: the semi-opaque background should extend all the way to sides of screen
- [x] Can we contain the background of the search bar to the max-width?
- [x] add padding to list items in nav (they are hard to click or read right now `padding: .25rem 0`

## Homepage again
- [x] WHEN YOU HAVE TIME (muahahahah): extend blue background left of the picture above the gold block (I know we talked about this, but just seeing it live I can't get over how odd it feels on a widescreen...sorry!)
  - [x] Change color to `$color-darkest-blue` https://github.com/CSIS-iLab/health-commission/blob/master/assets/_sass/pages/_home.scss#L182

## Header again
- [x] all articles link:
```css
.site-nav__menu .site-nav__dropdown-menu.all_work a::before {
left: calc(100% - 127px);
}

.site-nav__menu .site-nav__dropdown-menu.all_work a {
font-style: italic;
}
```
